import Head from "next/head";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/context/useAuth";
import { DEFAULT_SITE_CONFIG, type SiteConfig, type StoreLocation } from "@/lib/siteConfig";
import styles from "@/styles/adminSettings.module.css";

export default function AdminSettings(){
  const {currentUser,loading}=useAuth(); const [authorized,setAuthorized]=useState<boolean|null>(null); const [config,setConfig]=useState<SiteConfig>(DEFAULT_SITE_CONFIG); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
  useEffect(()=>{if(!currentUser)return setAuthorized(false);currentUser.getIdTokenResult().then(t=>setAuthorized(t.claims.role==="admin"));},[currentUser]);
  const request=useCallback(async(method="GET",body?:object)=>{if(!currentUser)throw new Error("Sesión no disponible.");const token=await currentUser.getIdToken();const response=await fetch("/api/admin/settings",{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||"No fue posible completar la acción.");return data;},[currentUser]);
  const load=useCallback(async()=>{try{setConfig(await request());setError("");}catch(e){setError(e instanceof Error?e.message:"Error inesperado.");}},[request]);
  useEffect(()=>{if(authorized)load();},[authorized,load]);
  function updateLocation(index:number,field:keyof StoreLocation,value:string){setConfig(current=>({...current,locations:current.locations.map((location,i)=>i===index?{...location,[field]:value}:location)}));}
  function addLocation(){setConfig(current=>({...current,locations:[...current.locations,{id:`ubicacion-${Date.now()}`,city:"",name:"",detail:"",phone:"",maps:""}]}));}
  function removeLocation(index:number){setConfig(current=>({...current,locations:current.locations.filter((_,i)=>i!==index)}));}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setSaved(false);try{const result=await request("PATCH",config);setConfig(current=>({...current,...result}));setSaved(true);setError("");}catch(e){setError(e instanceof Error?e.message:"No fue posible guardar.");}finally{setBusy(false);}}
  if(loading||authorized===null)return <main className={styles.state}>Verificando acceso…</main>;
  if(!authorized)return <main className={styles.state}><h1>Acceso reservado</h1><Link href="/my-account">Iniciar sesión</Link></main>;
  return <><Head><title>Configuración | Administración TECPOINT</title><meta name="robots" content="noindex,nofollow"/></Head><main className={styles.page}>
    <header><div><Link href="/admin">← Panel central</Link><p>CONFIGURACIÓN GENERAL</p><h1>Canales y ubicaciones.</h1></div><button form="settings-form" disabled={busy}>{busy?"Guardando…":"Guardar cambios"}</button></header>
    {error&&<div className={styles.error}>{error}</div>}{saved&&<div className={styles.success}>Cambios guardados. La web comenzará a utilizarlos inmediatamente.</div>}
    <section className={styles.integrations}><Status label="Meta Pixel" value={config.metaPixelId}/><Status label="Google Analytics" value={config.gaMeasurementId}/><Status label="Search Console" value={config.searchConsoleProperty}/></section>
    <form id="settings-form" onSubmit={submit}><section className={styles.block}><div><small>ATENCIÓN</small><h2>WhatsApp</h2><p>Utilice el formato internacional: 504 seguido del número, sin espacios.</p></div><div className={styles.fields}><label>Pedidos generales<input value={config.mainWhatsApp} onChange={e=>setConfig({...config,mainWhatsApp:e.target.value})}/></label><label>Tienda en línea<input value={config.onlineWhatsApp} onChange={e=>setConfig({...config,onlineWhatsApp:e.target.value})}/></label><label>Mayoreo<input value={config.wholesaleWhatsApp} onChange={e=>setConfig({...config,wholesaleWhatsApp:e.target.value})}/></label></div></section>
      <section className={styles.block}><div><small>PUNTOS DE ATENCIÓN</small><h2>Ubicaciones</h2><p>Cada punto aparece en la portada y el pie de página con WhatsApp y Google Maps.</p><button type="button" onClick={addLocation}>+ Agregar ubicación</button></div><div className={styles.locations}>{config.locations.map((location,index)=><article key={location.id}><div><b>0{index+1}</b><button type="button" onClick={()=>removeLocation(index)}>Quitar</button></div><label>Ciudad<input value={location.city} onChange={e=>updateLocation(index,"city",e.target.value)}/></label><label>Nombre<input value={location.name} onChange={e=>updateLocation(index,"name",e.target.value)}/></label><label>Dirección<input value={location.detail} onChange={e=>updateLocation(index,"detail",e.target.value)}/></label><label>WhatsApp<input value={location.phone} onChange={e=>updateLocation(index,"phone",e.target.value)}/></label><label>Enlace de Google Maps<input value={location.maps} onChange={e=>updateLocation(index,"maps",e.target.value)}/></label></article>)}</div></section>
      <section className={styles.block}><div><small>MEDICIÓN</small><h2>Integraciones</h2><p>Son identificadores públicos de medición. Nunca coloque contraseñas ni claves privadas aquí.</p></div><div className={styles.fields}><label>Meta Pixel ID<input value={config.metaPixelId} onChange={e=>setConfig({...config,metaPixelId:e.target.value})}/></label><label>Google Analytics ID<input value={config.gaMeasurementId} onChange={e=>setConfig({...config,gaMeasurementId:e.target.value})}/></label><label>Propiedad Search Console<input value={config.searchConsoleProperty} onChange={e=>setConfig({...config,searchConsoleProperty:e.target.value})}/></label><label>Verificación de Google<input value={config.googleSiteVerification} onChange={e=>setConfig({...config,googleSiteVerification:e.target.value})}/></label></div></section>
    </form>
  </main></>;
}
function Status({label,value}:{label:string;value:string}){return <article><span className={value?styles.on:styles.off}/><div><small>{label}</small><strong>{value?"Configurado":"Pendiente"}</strong></div></article>}
