import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/context/useAuth";
import { isAdminEmail } from "@/lib/adminAccess";
import styles from "@/styles/adminWholesale.module.css";

type Product = { id:string; sku:string; producto:string; brand:string; image:string; retailPrice:number; wholesalePrice:number; wholesaleEnabled:boolean; wholesaleCategory:string };
type Lead = { id:string; name:string; whatsapp:string; email:string; storeName:string; status:string; createdAt?:string|null };
type Pagination = { page:number; pageSize:number; totalItems:number; totalPages:number };

export default function AdminWholesale() {
  const { currentUser, loading } = useAuth();
  const [authorized,setAuthorized]=useState<boolean|null>(null);
  const [products,setProducts]=useState<Product[]>([]); const [leads,setLeads]=useState<Lead[]>([]);
  const [pagination,setPagination]=useState<Pagination>({page:1,pageSize:30,totalItems:0,totalPages:1}); const [summary,setSummary]=useState({active:0,categories:0});
  const [tab,setTab]=useState<"products"|"leads">("products"); const [query,setQuery]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{setAuthorized(isAdminEmail(currentUser?.email));},[currentUser]);
  const request=useCallback(async(method="GET",body?:object,path="/api/admin/wholesale")=>{if(!currentUser)throw new Error("Sesión no disponible.");const token=await currentUser.getIdToken();const response=await fetch(path,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||"No fue posible completar la acción.");return data;},[currentUser]);
  const loadProducts=useCallback(async(page=1,search=query)=>{setBusy(true);try{const data=await request("GET",undefined,`/api/admin/wholesale?view=products&page=${page}&query=${encodeURIComponent(search)}`);setProducts(data.products);setPagination(data.pagination);setSummary(data.summary);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible cargar Mayoreo.");}finally{setBusy(false);}},[request,query]);
  const loadLeads=useCallback(async()=>{setBusy(true);try{const data=await request("GET",undefined,"/api/admin/wholesale?view=leads");setLeads(data.leads);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible cargar solicitudes.");}finally{setBusy(false);}},[request]);
  useEffect(()=>{if(!authorized)return;const timer=window.setTimeout(()=>loadProducts(1,query),query?350:0);return()=>window.clearTimeout(timer);},[authorized,query,loadProducts]);
  const visible=useMemo(()=>products,[products]);
  const categories=useMemo(()=>Array.from(new Set(products.map(product=>product.wholesaleCategory).filter(Boolean))).sort(),[products]);
  async function saveProduct(event:FormEvent<HTMLFormElement>,product:Product){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);try{await request("PATCH",{target:"product",id:product.id,wholesalePrice:data.get("wholesalePrice"),wholesaleCategory:data.get("wholesaleCategory"),wholesaleEnabled:data.get("wholesaleEnabled")==="on"});await loadProducts(pagination.page);}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible guardar.");setBusy(false);}}
  async function updateLead(lead:Lead,status:string){setBusy(true);try{await request("PATCH",{target:"lead",id:lead.id,status});await loadLeads();}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible actualizar.");setBusy(false);}}
  if(loading||authorized===null)return <main className={styles.state}>Verificando acceso…</main>;
  if(!authorized)return <main className={styles.state}><h1>Acceso reservado</h1><Link href="/my-account">Iniciar sesión</Link></main>;
  return <><Head><title>Mayoreo | Administración TECPOINT</title><meta name="robots" content="noindex,nofollow"/></Head><main className={styles.page}>
    <header><div><Link href="/admin">← Panel central</Link><p>GESTIÓN MAYORISTA</p><h1>Mayoreo.</h1></div><button onClick={()=>tab==="products"?loadProducts(pagination.page):loadLeads()} disabled={busy}>{busy?"Actualizando…":"Actualizar datos"}</button></header>
    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Productos activos</span><strong>{summary.active}</strong></article><article><span>Categorías</span><strong>{summary.categories}</strong></article><article><span>Solicitudes cargadas</span><strong>{leads.length}</strong></article></section>
    <nav className={styles.tabs}><button className={tab==="products"?styles.selected:""} onClick={()=>setTab("products")}>Productos y categorías</button><button className={tab==="leads"?styles.selected:""} onClick={()=>{setTab("leads");if(!leads.length)loadLeads();}}>Solicitudes recibidas</button></nav>
    {tab==="products"?<><div className={styles.tools}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar producto, SKU, marca o categoría"/><span>{pagination.totalItems} productos</span></div><section className={styles.productList}>{visible.map(product=><details key={product.id}><summary><div className={styles.productIdentity}>{product.image?<Image src={encodeURI(product.image)} alt="" width={72} height={72} unoptimized/>:<span className={styles.noImage}>Sin imagen</span>}<div><strong>{product.producto||"Producto sin nombre"}</strong><small>{product.sku} · {product.brand||"Sin marca"}</small></div></div><div className={styles.badges}>{product.wholesaleEnabled&&product.wholesalePrice>0?<b>VISIBLE EN MAYOREO</b>:<em>OCULTO</em>}<span>{product.wholesaleCategory||"Sin categoría"}</span></div></summary><form onSubmit={event=>saveProduct(event,product)}><label>Precio de mayoreo<input name="wholesalePrice" type="number" min="0" step="0.01" defaultValue={product.wholesalePrice}/></label><label>Categoría de mayoreo<input name="wholesaleCategory" list="wholesale-categories" defaultValue={product.wholesaleCategory}/></label><label className={styles.check}><input name="wholesaleEnabled" type="checkbox" defaultChecked={product.wholesaleEnabled}/>Mostrar en catálogo de Mayoreo</label><p>Precio de detalle actual: L {product.retailPrice.toLocaleString("es-HN",{minimumFractionDigits:2})}</p><button disabled={busy}>Guardar cambios</button></form></details>)}</section>{pagination.totalPages>1&&<nav className={styles.tools}><button disabled={busy||pagination.page===1} onClick={()=>loadProducts(pagination.page-1)}>Anterior</button><span>Página {pagination.page} de {pagination.totalPages}</span><button disabled={busy||pagination.page===pagination.totalPages} onClick={()=>loadProducts(pagination.page+1)}>Siguiente</button></nav>}<datalist id="wholesale-categories">{categories.map(category=><option key={category} value={category}/>)}</datalist></>:<section className={styles.leads}>{leads.length?leads.map(lead=><article key={lead.id}><div><small>{lead.createdAt?new Date(lead.createdAt).toLocaleString("es-HN"):"Fecha pendiente"}</small><h2>{lead.storeName||"Tienda sin nombre"}</h2><p>{lead.name} · {lead.whatsapp}</p><a href={`mailto:${lead.email}`}>{lead.email}</a></div><select value={lead.status} onChange={event=>updateLead(lead,event.target.value)}><option value="new">Nueva</option><option value="contacted">Contactada</option><option value="approved">Aprobada</option><option value="closed">Cerrada</option></select></article>):<div className={styles.empty}>Todavía no hay solicitudes de Mayoreo.</div>}</section>}
  </main></>;
}
